### ISSUE TITLE
Minor quip: Prints error if no data created 

### ISSUE THREAD

**Issue by adishavit** [biggzlar/opencv_js_compiler#4]
Building the example, ends with the following error:
```
data created: False
Traceback (most recent call last):
  File "n_make.py", line 238, in <module>
    print os.path.getsize(os.path.join(js_build_path, 'cv.data')) / 1000000.0, 'mb', '\n'
  File "/usr/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: '../../web_build/cv.data'
```
though everything is OK.

**Comment by biggzlar** [comment]
Did a little rewrite on the end report: 
https://github.com/biggzlar/opencv_js_compiler/commit/570705fb92a8efda1dd7e2b22ef64b746e5d4dae
