### ISSUE TITLE
OpenCV Module Issues

### ISSUE THREAD

**Issue by Neuroforge** [biggzlar/opencv_js_compiler#8]
Ok. I thought i had my issues ironed out. Sadly not. :)

When building there is some issue with DetectionBasedTracker from the Object Detect module.

If i switch this off, in n_make.py OpenCV will then complete it's build!!

                     '-DBUILD_opencv_objdetect=OFF',

Here is the output for the Object Detect issue..... followed by my current issue.

> [ 89%] Building CXX object modules/objdetect/CMakeFiles/opencv_objdetect.dir/src/detection_based_tracker.cpp.o
> /Users/daniel/Documents/opencv_js_compiler/opencv/modules/objdetect/src/detection_based_tracker.cpp:124:11: error: no member named 'DetectionBasedTracker' in namespace 'cv'
> class cv::DetectionBasedTracker::SeparateDetectionWork
>       ~~~~^
> /Users/daniel/Documents/opencv_js_compiler/opencv/modules/objdetect/src/detection_based_tracker.cpp:192:5: error: no member named 'DetectionBasedTracker' in namespace 'cv'
> cv::DetectionBasedTracker::SeparateDetectionWork::SeparateDetectionWork(DetectionBasedTracker& _detectionBasedTracker, cv::Ptr<DetectionBasedTracker::IDetector> _detector)
> ~~~~^
> /Users/daniel/Documents/opencv_js_compiler/opencv/modules/objdetect/src/detection_based_tracker.cpp:192:128: error: use of undeclared identifier 'DetectionBasedTracker'
> cv::DetectionBasedTracker::SeparateDetectionWork::SeparateDetectionWork(DetectionBasedTracker& _detectionBasedTracker, cv::Ptr<DetectionBasedTracker::IDetector> _detector)
>                                                                                                                                ^
> /Users/daniel/Documents/opencv_js_compiler/opencv/modules/objdetect/src/detection_based_tracker.cpp:192:73: error: unknown type name 'DetectionBasedTracker'
> cv::DetectionBasedTracker::SeparateDetectionWork::SeparateDetectionWork(DetectionBasedTracker& _detectionBasedTracker, cv::Ptr<DetectionBasedTracker::IDetector> _detector)
>                                                                         ^
> /Users/daniel/Documents/opencv_js_compiler/opencv/modules/objdetect/src/detection_based_tracker.cpp:229:5: error: no member named 'DetectionBasedTracker' in namespace 'cv'
> cv::DetectionBasedTracker::SeparateDetectionWork::~SeparateDetectionWork()
> ~~~~^
> /Users/daniel/Documents/opencv_js_compiler/opencv/modules/objdetect/src/detection_based_tracker.cpp:240:10: error: no member named 'DetectionBasedTracker' in namespace 'cv'
> bool cv::DetectionBasedTracker::SeparateDetectionWork::run()
>      ~~~~^
> /Users/daniel/Documents/opencv_js_compiler/opencv/modules/objdetect/src/detection_based_tracker.cpp:285:31: error: no member named 'DetectionBasedTracker' in namespace 'cv'
>     CATCH_ALL_AND_LOG({ ((cv::DetectionBasedTracker::SeparateDetectionWork*)p)->workcycleObjectDetector(); });
>                           ~~~~^
> /Users/daniel/Documents/opencv_js_compiler/opencv/modules/objdetect/src/detection_based_tracker.cpp:273:9: note: expanded from macro 'CATCH_ALL_AND_LOG'
>         _block;                                                                             \
>         ^~~~~~
> /Users/daniel/Documents/opencv_js_compiler/opencv/modules/objdetect/src/detection_based_tracker.cpp:285:76: error: expected expression
>     CATCH_ALL_AND_LOG({ ((cv::DetectionBasedTracker::SeparateDetectionWork*)p)->workcycleObjectDetector(); });
>                                                                            ^
> /Users/daniel/Documents/opencv_js_compiler/opencv/modules/objdetect/src/detection_based_tracker.cpp:287:15: error: no member named 'DetectionBasedTracker' in namespace 'cv'
>         ((cv::DetectionBasedTracker::SeparateDetectionWork*)p)->lock();
>           ~~~~^
> /Users/daniel/Documents/opencv_js_compiler/opencv/modules/objdetect/src/detection_based_tracker.cpp:287:60: error: expected expression
>         ((cv::DetectionBasedTracker::SeparateDetectionWork*)p)->lock();
>                                                            ^
> /Users/daniel/Documents/opencv_js_compiler/opencv/modules/objdetect/src/detection_based_tracker.cpp:288:15: error: no member named 'DetectionBasedTracker' in namespace 'cv'
>         ((cv::DetectionBasedTracker::SeparateDetectionWork*)p)->stateThread = cv::DetectionBasedTracker::SeparateDetectionWork::STATE_THREAD_STOPPED;
>           ~~~~^
> /Users/daniel/Documents/opencv_js_compiler/opencv/modules/objdetect/src/detection_based_tracker.cpp:288:60: error: expected expression
>         ((cv::DetectionBasedTracker::SeparateDetectionWork*)p)->stateThread = cv::DetectionBasedTracker::SeparateDetectionWork::STATE_THREAD_STOPPED;
>                                                            ^
> /Users/daniel/Documents/opencv_js_compiler/opencv/modules/objdetect/src/detection_based_tracker.cpp:288:83: error: no member named 'DetectionBasedTracker' in namespace 'cv'
>         ((cv::DetectionBasedTracker::SeparateDetectionWork*)p)->stateThread = cv::DetectionBasedTracker::SeparateDetectionWork::STATE_THREAD_STOPPED;
>                                                                               ~~~~^
> /Users/daniel/Documents/opencv_js_compiler/opencv/modules/objdetect/src/detection_based_tracker.cpp:289:15: error: no member named 'DetectionBasedTracker' in namespace 'cv'
>         ((cv::DetectionBasedTracker::SeparateDetectionWork*)p)->isObjectDetectingReady=false;
>           ~~~~^
> /Users/daniel/Documents/opencv_js_compiler/opencv/modules/objdetect/src/detection_based_tracker.cpp:289:60: error: expected expression
>         ((cv::DetectionBasedTracker::SeparateDetectionWork*)p)->isObjectDetectingReady=false;
>                                                            ^
> /Users/daniel/Documents/opencv_js_compiler/opencv/modules/objdetect/src/detection_based_tracker.cpp:290:15: error: no member named 'DetectionBasedTracker' in namespace 'cv'
>         ((cv::DetectionBasedTracker::SeparateDetectionWork*)p)->shouldObjectDetectingResultsBeForgot=false;
>           ~~~~^
> /Users/daniel/Documents/opencv_js_compiler/opencv/modules/objdetect/src/detection_based_tracker.cpp:290:60: error: expected expression
>         ((cv::DetectionBasedTracker::SeparateDetectionWork*)p)->shouldObjectDetectingResultsBeForgot=false;
>                                                            ^
> /Users/daniel/Documents/opencv_js_compiler/opencv/modules/objdetect/src/detection_based_tracker.cpp:292:15: error: no member named 'DetectionBasedTracker' in namespace 'cv'
>         ((cv::DetectionBasedTracker::SeparateDetectionWork*)p)->objectDetectorThreadStartStop.notify_one();
>           ~~~~^
> /Users/daniel/Documents/opencv_js_compiler/opencv/modules/objdetect/src/detection_based_tracker.cpp:292:60: error: expected expression
>         ((cv::DetectionBasedTracker::SeparateDetectionWork*)p)->objectDetectorThreadStartStop.notify_one();
>                                                            ^
> fatal error: too many errors emitted, stopping now [-ferror-limit=]
> 20 errors generated.
> ERROR:root:compiler frontend failed to generate LLVM bitcode, halting
> make[2]: *** [modules/objdetect/CMakeFiles/opencv_objdetect.dir/src/detection_based_tracker.cpp.o] Error 1
> make[1]: *** [modules/objdetect/CMakeFiles/opencv_objdetect.dir/all] Error 2
> make: *** [all] Error 2
> Traceback (most recent call last):
>   File "n_make.py", line 159, in <module>
>     emscripten.Building.make(['make'])
>   File "/Users/daniel/Documents/emsdk-portable/emscripten/1.37.33/tools/shared.py", line 1558, in make
>     raise subprocess.CalledProcessError(cmd=args, returncode=process.returncode)
> subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2
> Hal:opencv_js_compiler daniel$  python n_make.py example/example.cpp

This is sorted out when you remove the object detect module from building......

HOWEVER.....

                     '-DBUILD_opencv_features2d=ON',

This adds features 2D module so that this line in n_make.py now works.....

    input_files = [
        os.path.join('lib', 'libopencv_features2d.a'),
]

However.....

On stage 5 of the build process i get the following error.... :(

> WARNING:root:not all asm.js optimizations are possible with ALLOW_MEMORY_GROWTH, disabling those. [-Walmost-asm]
> INFO:root:generating system library: libcxx.a... (this will be cached in "/Users/daniel/.emscripten_cache/asmjs/libcxx.a" for subsequent builds)
> INFO:root: - ok
> 0  llc                      0x00000001079c2028 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 40
> 1  llc                      0x00000001079c2656 SignalHandler(int) + 358
> 2  libsystem_platform.dylib 0x00007fff72070f5a _sigtramp + 26
> 3  libsystem_malloc.dylib   0x00007fff71f991b2 small_malloc_from_free_list + 436
> 4  llc                      0x000000010752fe18 llvm::legacy::PassManagerImpl::run(llvm::Module&) + 920
> 5  llc                      0x0000000106da9ae9 compileModule(char**, llvm::LLVMContext&) + 11097
> 6  llc                      0x0000000106da6bcb main + 1163
> 7  libdyld.dylib            0x00007fff71def115 start + 1
> 8  libdyld.dylib            0x000000000000000c start + 2384531192
> Stack dump:
> 0.  Program arguments: /Users/daniel/Documents/emsdk-portable/clang/e1.37.33_64bit/llc /tmp/tmps8YJRs/cv.bc -march=js -filetype=asm -o /tmp/tmpXILyFn.4.js -emscripten-stack-size=5242880 -O3 -emscripten-assertions=2 -emscripten-global-base=8 -enable-emscripten-cpp-exceptions -emscripten-no-exit-runtime 
> 1.  Running pass 'Expand and lower illegal >i32 operations into 32-bit chunks' on module '/tmp/tmps8YJRs/cv.bc'.
> Traceback (most recent call last):
>   File "/Users/daniel/Documents/emsdk-portable/emscripten/1.37.33/emcc.py", line 2786, in <module>
>     run()
>   File "/Users/daniel/Documents/emsdk-portable/emscripten/1.37.33/emcc.py", line 1611, in run
>     final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
>   File "/Users/daniel/Documents/emsdk-portable/emscripten/1.37.33/tools/shared.py", line 2009, in emscripten
>     call_emscripten(cmdline)
>   File "/Users/daniel/Documents/emsdk-portable/emscripten/1.37.33/emscripten.py", line 2340, in _main
>     temp_files.run_and_clean(lambda: main(
>   File "/Users/daniel/Documents/emsdk-portable/emscripten/1.37.33/tools/tempfiles.py", line 93, in run_and_clean
>     return func()
>   File "/Users/daniel/Documents/emsdk-portable/emscripten/1.37.33/emscripten.py", line 2345, in <lambda>
>     DEBUG=DEBUG,
>   File "/Users/daniel/Documents/emsdk-portable/emscripten/1.37.33/emscripten.py", line 2251, in main
>     temp_files=temp_files, DEBUG=DEBUG)
>   File "/Users/daniel/Documents/emsdk-portable/emscripten/1.37.33/emscripten.py", line 94, in emscript
>     backend_output = compile_js(infile, settings, temp_files, DEBUG)
>   File "/Users/daniel/Documents/emsdk-portable/emscripten/1.37.33/emscripten.py", line 123, in compile_js
>     shared.jsrun.timeout_run(subprocess.Popen(backend_args, stdout=subprocess.PIPE, universal_newlines=True), note_args=backend_args)
>   File "/Users/daniel/Documents/emsdk-portable/emscripten/1.37.33/tools/jsrun.py", line 20, in timeout_run
>     raise Exception('Subprocess "' + ' '.join(note_args) + '" failed with exit code ' + str(proc.returncode) + '!')
> Exception: Subprocess "/Users/daniel/Documents/emsdk-portable/clang/e1.37.33_64bit/llc /tmp/tmps8YJRs/cv.bc -march=js -filetype=asm -o /tmp/tmpXILyFn.4.js -emscripten-stack-size=5242880 -O3 -emscripten-assertions=2 -emscripten-global-base=8 -enable-emscripten-cpp-exceptions -emscripten-no-exit-runtime" failed with exit code -11!
> Traceback (most recent call last):
>   File "n_make.py", line 237, in <module>
>     emscripten.Building.emcc('linked_input.bc', emcc_args, opencv)
>   File "/Users/daniel/Documents/emsdk-portable/emscripten/1.37.33/tools/shared.py", line 1985, in emcc
>     assert os.path.exists(output_filename), 'emcc could not create output file: ' + output_filename
> AssertionError: emcc could not create output file: ../../web_build/cv.html

Any thoughts on this issue?

**Comment by biggzlar** [comment]
Not right now, I'll have to look at it in the morning.

**Comment by Neuroforge** [comment]
No worries. Speak soon.

Found a similar issue here that was "fixed" back in 2014.

https://github.com/kripken/emscripten/issues/2539

This is happening at line 235.

    emscripten.Building.emcc('linked_input.bc', emcc_args, opencv)
